### ISSUE TITLE
Shotgun sometimes pops in and out of it's place

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#12]
This does not happen with the pistol or crowbar. they have this "wrong alignment after level chapter load". The shotgun seems to pop out of it's pivot.

**Comment by baggyg** [comment]
I don't have the Shotgun in the main game yet but I've seen this very often in MP. However I do suspect it is the same issue as the pistol crowbar.

**Comment by cercata** [comment]
> I do suspect it is the same issue as the pistol crowbar.

With the pistol I never have issues
With the crowbar, it happens after a loading screen, and it gets fixed with the change weapon trick

But this thing on shotgun is different, it's like some kind of controller drift, or tracking lost during a short period ...
For some seconds the shotgun moves like 30cm away of you, and then it comes back

**Comment by neitey** [comment]
> I don't have the Shotgun in the main game yet but I've seen this very often in MP. However I do suspect it is the same issue as the pistol crowbar.

Definetly not with the pistol and crowbar or rifle. Just the shotgun.

**Comment by DrBeef** [comment]
SvenViking suggested it might be the idle animation for the shotgun.. which is the best contender for the reason so far. I will disable the idle animation and see if it still happens, if not then that's a good place to start looking.

**Comment by DrBeef** [comment]
Closing this, as this will be resolved in the next release
