### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Blueforcer** [DrBeef/Lambda1VR#14]
is it possible to change the language to german?

**Comment by cercata** [comment]
You mean the text or the voices ?

For voices, it can be done by copying files from your instalation, you have an aditional folder with content on you steam languaje

**Comment by neitey** [comment]
Pretty easy. copy the content of steam/common/halflife/valve/valve_german to your quest xash/valve.
just copy resource and sound folder or you'll get the "non-violence" censored version.

I would also suggest to only copy the some parts of the sound folder since the soldiers and the public announcement system sounds pretty bad in german. Barney is the best in german though, "Ja, ich kann nich Gordon' bin im Dienst, ich geb dir später ein Bier aus.

I love that barney says "Gordon" and "du" intead of the formal "Mr.Freeman"

**Comment by neitey** [comment]
can be closed
