### ISSUE TITLE
App crash when it loads next area

### ISSUE THREAD

**Issue by Jervi71** [DrBeef/Lambda1VR#40]
Hi,
I have last Lambda ver 1.1.0 and Quest with last firmware (9.0).
During game when it loads next area, app crashes and I return to Quest Home.
Before I update with last Lambda version, I have deleted config.cfg from valve folder.

**Comment by neitey** [comment]
Does it crash on any next-area-load or is it a specific one? Do you use the HD Texture Pack (HL:GOLD) or the valve_hd folder?

**Comment by Jervi71** [comment]
@neitey
Any next area load.
Yes, I use HD Texture Pack optimized for Lambda1VR.

**Comment by neitey** [comment]
So 

> @neitey
> Any next area load.
> Yes, I use HD Texture Pack optimized for Lambda1VR.

So it crashes on the first area load? Like in the intro or the first steps in the black mesa?

That is very strange. I am playing with HL:Gold Textures (the ones on reddit) and it works.

**Comment by Jervi71** [comment]
@neitey
I'm playing in area after the elevator that going down where there is a sewage channel to cross. The problem is when load next area in the corridors behind the doors.

I continue from an old savegame.
I installed hd texture before update.

**Comment by neitey** [comment]
[Solution] Fix for random level transition crashes! It's the Lasersight!
Headcrab hunter and hero of the day u/Inimitable found the fix for the random crashes happening between level transition loads. It is the LASER SIGHT. Disable it before transition loading! 
I  tested this fix and it's working. 
HD Textures are not related to the crashes, as it seems. So they are save to use.

**Comment by Jervi71** [comment]
@neitey
Yes! Is the laser sight! For now I keep it disable but I hope it is early fixed.
Thanks!

**Comment by baggyg** [comment]
Fixed in latest release (v1.1.1)
