### ISSUE TITLE
Takes long time between new areas being loaded

### ISSUE THREAD

**Issue by VintageMilk** [DrBeef/Lambda1VR#97]
I haven’t played the game in a while (3 months) and I came back to it only to find it takes around two minutes between loading screens. Can anyone help me here?

**Comment by baggyg** [comment]
We have had reports of loading time issues. This is due to OS changes by Meta / Oculus especially on the Public test Channel (PTC) and nothing to do with the apps themselves (people have also reported this in other store apps). In cases where it has appeared, it has also seemed to disappear either with the next update or somewhat randomly. 

Unfortunately this is completely out of our control and its down to Oculus to fix the underlying bug, which they may well have done in more recent versions. If you have this issue, we suggest making sure you are on the latest OS available to you, restarting the headset and trying again. Some users has found that uninstalling and reinstalling the app has helped (no need to delete the files themselves, so save games will be retained).

**Comment by eq-soft** [comment]
@VintageMilk, try to use original HD distro (it takes about 450Mb) or even pure original distro. I had exactly the same issue with my distro (2.5Gb) that previously worked fine on the same device and using of such small distro fixed it.
