### ISSUE TITLE
Weapon(hands) is not in the range of the sight

### ISSUE THREAD

**Issue by Rntver** [DrBeef/Lambda1VR#99]
It seems weapon should be in front of me but its not. When I had a crowbar its not visible and to use it I had to get at close range and even that was no guarantee that Im using it cuz it behind me. When I got a pistol **I activated laser it comes from behind my left shoulder and lasers through me**. I can assume that camera is shifted to the front and right of my weapon for 1-2 meters and lil down. Was installing all as instruction says, oculus update was 54v, re-installation wasnt useful.

**Comment by xidarian** [comment]
I am having the same issue. It's a brand new quest 2 and the game runs great but I can't see the crowbar or any guns. The laser comes from behind me if I turn it on.

**Comment by Sl0vi** [comment]
Version 1.6.2 seems to be broken, I was having this exact same issue (Plus some issues getting the game to even launch because it couldn't get past the file permissions dialog)

I tried downgrading to version 1.5.1, which is available from the releases page and the weapons appear in the correct position in that version.

So, for now, the workaround is to manually install the apk for version 1.5.1.

**Comment by baggyg** [comment]
You don't need to install manually the APK as a workaround. 

The official version for Quest is 1.5.1 and that is the one that is on the official Sidequest release. 

https://sidequestvr.com/app/124/lambda1vr-half-life-in-vr
